accelerate launch test_one.py \
    --model_type bert \
    --pretrained_model_name_or_path hfl/chinese-roberta-wwm-ext \
    --logging_steps 5000 \
    --num_train_epochs 150 \
    --learning_rate 1e-5 \
    --num_warmup_steps_or_radios 0.1 \
    --gradient_accumulation_steps 1 \
    --per_device_train_batch_size 20 \
    --per_device_eval_batch_size 20 \
    --seed 42 \
    --save_steps 10000 \
    --output_dir ./outputs \
    --max_length 256